### ISSUE TITLE
Support BEP 42

### ISSUE THREAD

**Issue by raptortech-js** [feross/ut_metadata#18]
It may be worth adding support for [BEP 42](http://www.bittorrent.org/beps/bep_0042.html) to lay the groundwork for better security of the Bittorrent DHT.

**Comment by nhdms** [comment]
Sorry how can I use this module independently? (I have list peer and infohash)
Thanks.

**Comment by feross** [comment]
@raptortech-js You're right. BEP 42 support in WebTorrent would be great. But I don't think that it requires any changes to `bittorrent-protocol`. You're looking for `bittorrent-dht`. There's even an issue for it already: https://github.com/feross/bittorrent-dht/issues/15

**Comment by feross** [comment]
@nhdms See the README. If still have issues, please open a new issue instead of commenting in unrelated issues. Thanks.
