### ISSUE TITLE
crash with webtorrent wire

### ISSUE THREAD

**Issue by pomel5** [feross/ut_metadata#20]
wire = torrent.wires[1];
wire.use(ut_metadata());
wire.ut_metadata.on('metadata', function (metadata) {});

results in crash:

ut_metadata\index.js:189
    buf.copy(this.metadata, piece * PIECE_LENGTH)
        ^

TypeError: argument should be a Buffer
    at TypeError (native)
    at utMetadata._onData (\ut_metadata\index.js:189:9)

**Comment by feross** [comment]
In your example, is `torrent` a torrent object from WebTorrent? `ut_metadata` is already applied to the wire, so doing this again will definitely not work.

**Comment by pomel5** [comment]
Yes its torrent object from webtorrent. Whats proper way to get metadata from wire?
removed "wire.use(ut_metadata());" and added "wire.ut_metadata.fetch();" but it still does not give me metadata.

wire.ut_metadata.fetch();
wire.ut_metadata.on('metadata', function (metadata) {
	console.log("received metadata");
});

Thanks

**Comment by feross** [comment]
Do not use `ut_metadata` directly. This is already used internally by `webtorrent`.

Try this instead: 

```js
`torrent.on('metadata', function (metadata) {})`
```

**Comment by pomel5** [comment]
Thanks for help. but this does not works (metadata event is not fired):

client.add(magnetURI, function (torrent) {
torrent.on('metadata', function (metadata) {})
});

but this works:
client.add(magnetURI, function (torrent) {
if (torrent.metadata!=null) console.log("we have metadata");
});
