### ISSUE TITLE
Could you refactory ut_metadata and bittorrent-protocol?

### ISSUE THREAD

**Issue by Fuck-You-GFW** [feross/ut_metadata#8]
Hi, I am interested in your ut_metadata and bittorrent-protocol. I have been reading  the two projects for many days, but I am very confused your code. It is very difficult to understand. Could you refactory it and make it easy to understand?

I am sorry the unreasonable question.

**Comment by feross** [comment]
If you have specific questions about how these packages work, you can ask me and I'll do my best to answer.

**Comment by Fuck-You-GFW** [comment]
I understood how they work now, although I am still incomprehensible in the code. But It is no matter, I copy the some code to my project. :)

Thank you very much!
